
package hw5.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.4.3
 * Sun Apr 11 14:34:05 CEST 2021
 * Generated source version: 3.4.3
 */

@XmlRootElement(name = "addYoghurt", namespace = "http://apolicky.cz/nswi145/yoghurtEshop")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addYoghurt", namespace = "http://apolicky.cz/nswi145/yoghurtEshop", propOrder = {"count", "flavor_id"})

public class AddYoghurt {

    @XmlElement(name = "count")
    private int count;
    @XmlElement(name = "flavor_id")
    private int flavor_id;

    public int getCount() {
        return this.count;
    }

    public void setCount(int newCount)  {
        this.count = newCount;
    }

    public int getFlavor_id() {
        return this.flavor_id;
    }

    public void setFlavor_id(int newFlavor_id)  {
        this.flavor_id = newFlavor_id;
    }

}

