
package hw5.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.4.3
 * Sun Apr 11 14:34:05 CEST 2021
 * Generated source version: 3.4.3
 */

@XmlRootElement(name = "cancelOrderResponse", namespace = "http://apolicky.cz/nswi145/yoghurtEshop")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cancelOrderResponse", namespace = "http://apolicky.cz/nswi145/yoghurtEshop")

public class CancelOrderResponse {

    @XmlElement(name = "cancel_success")
    private boolean cancel_success;

    public boolean getCancel_success() {
        return this.cancel_success;
    }

    public void setCancel_success(boolean newCancel_success)  {
        this.cancel_success = newCancel_success;
    }

}

