package cz.apolicky.nswi145.yoghurteshop;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.3
 * 2021-04-11T19:16:10.045+02:00
 * Generated source version: 3.4.3
 *
 */
@WebService(targetNamespace = "http://apolicky.cz/nswi145/yoghurtEshop", name = "eshopInterface")
@XmlSeeAlso({ObjectFactory.class})
public interface EshopInterface {

    @WebMethod
    @RequestWrapper(localName = "cancelOrder", targetNamespace = "http://apolicky.cz/nswi145/yoghurtEshop", className = "cz.apolicky.nswi145.yoghurteshop.CancelOrder")
    @ResponseWrapper(localName = "cancelOrderResponse", targetNamespace = "http://apolicky.cz/nswi145/yoghurtEshop", className = "cz.apolicky.nswi145.yoghurteshop.CancelOrderResponse")
    @WebResult(name = "cancel_success", targetNamespace = "")
    public boolean cancelOrder()
;

    @WebMethod
    @RequestWrapper(localName = "addYoghurt", targetNamespace = "http://apolicky.cz/nswi145/yoghurtEshop", className = "cz.apolicky.nswi145.yoghurteshop.AddYoghurt")
    @ResponseWrapper(localName = "addYoghurtResponse", targetNamespace = "http://apolicky.cz/nswi145/yoghurtEshop", className = "cz.apolicky.nswi145.yoghurteshop.AddYoghurtResponse")
    @WebResult(name = "add_success", targetNamespace = "")
    public boolean addYoghurt(

        @WebParam(name = "count", targetNamespace = "")
        int count,
        @WebParam(name = "flavor_id", targetNamespace = "")
        int flavorId
    );

    @WebMethod
    @RequestWrapper(localName = "totalAmount", targetNamespace = "http://apolicky.cz/nswi145/yoghurtEshop", className = "cz.apolicky.nswi145.yoghurteshop.TotalAmount")
    @ResponseWrapper(localName = "totalAmountResponse", targetNamespace = "http://apolicky.cz/nswi145/yoghurtEshop", className = "cz.apolicky.nswi145.yoghurteshop.TotalAmountResponse")
    public void totalAmount(

        @WebParam(mode = WebParam.Mode.INOUT, name = "total_amount", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> totalAmount
    );
}
