
package cz.apolicky.nswi145.yoghurteshop;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.HashMap;
import java.util.Map;

import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import org.apache.cxf.endpoint.Client;
import org.apache.cxf.endpoint.Endpoint;
import org.apache.cxf.frontend.ClientProxy;
import org.apache.cxf.ws.security.wss4j.WSS4JOutInterceptor;
import org.apache.wss4j.dom.WSConstants;
import org.apache.wss4j.dom.handler.WSHandlerConstants;

/**
 * This class was generated by Apache CXF 3.4.3
 * 2021-04-11T19:16:09.930+02:00
 * Generated source version: 3.4.3
 *
 */
public final class EshopInterface_EshopImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://apolicky.cz/nswi145/yoghurtEshop", "EshopImplService");

    private EshopInterface_EshopImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = EshopImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        EshopImplService ss = new EshopImplService(wsdlURL, SERVICE_NAME);
        EshopInterface port = ss.getEshopImplPort();
        
//        http://cxf.apache.org/docs/ws-security.html#WS-Security-UsernameTokenAuthentication
        
        Endpoint cxfEndpoint = ClientProxy.getClient(port).getEndpoint();
        
        Map<String,Object> outProps = new HashMap<String,Object>();
        outProps.put(WSHandlerConstants.ACTION, WSHandlerConstants.USERNAME_TOKEN);
        outProps.put(WSHandlerConstants.USER, "Alice");
        outProps.put(WSHandlerConstants.PASSWORD_TYPE, WSConstants.PW_TEXT);
        outProps.put(WSHandlerConstants.PW_CALLBACK_CLASS, 
        		hw5.OutPasswordCallback.class.getName());
         
        WSS4JOutInterceptor wssOut = new WSS4JOutInterceptor(outProps);
        cxfEndpoint.getOutInterceptors().add(wssOut);

        {
        System.out.println("Invoking cancelOrder...");
        boolean _cancelOrder__return = port.cancelOrder();
        System.out.println("cancelOrder.result=" + _cancelOrder__return);


        }
        {
        System.out.println("Invoking addYoghurt...");
        int _addYoghurt_count = -438623705;
        int _addYoghurt_flavorId = 263217170;
        boolean _addYoghurt__return = port.addYoghurt(_addYoghurt_count, _addYoghurt_flavorId);
        System.out.println("addYoghurt.result=" + _addYoghurt__return);


        }
        {
        System.out.println("Invoking totalAmount...");
        int _totalAmount_totalAmountVal = 699904227;
        javax.xml.ws.Holder<java.lang.Integer> _totalAmount_totalAmount = new javax.xml.ws.Holder<java.lang.Integer>(_totalAmount_totalAmountVal);
        port.totalAmount(_totalAmount_totalAmount);

        System.out.println("totalAmount._totalAmount_totalAmount=" + _totalAmount_totalAmount.value);

        }

        System.exit(0);
    }

}
