package cz.apolicky.nswi145.yoghurteshop;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.3
 * 2021-04-11T19:16:10.053+02:00
 * Generated source version: 3.4.3
 *
 */
@WebServiceClient(name = "EshopImplService",
                  wsdlLocation = "http://localhost:8080/lab05/services/EshopImplPort?wsdl",
                  targetNamespace = "http://apolicky.cz/nswi145/yoghurtEshop")
public class EshopImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://apolicky.cz/nswi145/yoghurtEshop", "EshopImplService");
    public final static QName EshopImplPort = new QName("http://apolicky.cz/nswi145/yoghurtEshop", "EshopImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/lab05/services/EshopImplPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EshopImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/lab05/services/EshopImplPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EshopImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EshopImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EshopImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public EshopImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public EshopImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EshopImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns EshopInterface
     */
    @WebEndpoint(name = "EshopImplPort")
    public EshopInterface getEshopImplPort() {
        return super.getPort(EshopImplPort, EshopInterface.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EshopInterface
     */
    @WebEndpoint(name = "EshopImplPort")
    public EshopInterface getEshopImplPort(WebServiceFeature... features) {
        return super.getPort(EshopImplPort, EshopInterface.class, features);
    }

}
