
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package cz.apolicky.nswi145.yoghurteshop;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.3
 * 2021-04-11T19:16:10.029+02:00
 * Generated source version: 3.4.3
 *
 */

@javax.jws.WebService(
                      serviceName = "EshopImplService",
                      portName = "EshopImplPort",
                      targetNamespace = "http://apolicky.cz/nswi145/yoghurtEshop",
                      wsdlLocation = "http://localhost:8080/lab05/services/EshopImplPort?wsdl",
                      endpointInterface = "cz.apolicky.nswi145.yoghurteshop.EshopInterface")

public class EshopImplPortImpl implements EshopInterface {

    private static final Logger LOG = Logger.getLogger(EshopImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see cz.apolicky.nswi145.yoghurteshop.EshopInterface#cancelOrder()*
     */
    public boolean cancelOrder() {
        LOG.info("Executing operation cancelOrder");
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see cz.apolicky.nswi145.yoghurteshop.EshopInterface#addYoghurt(int count, int flavorId)*
     */
    public boolean addYoghurt(int count, int flavorId) {
        LOG.info("Executing operation addYoghurt");
        System.out.println(count);
        System.out.println(flavorId);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see cz.apolicky.nswi145.yoghurteshop.EshopInterface#totalAmount(java.lang.Integer totalAmount)*
     */
    public void totalAmount(javax.xml.ws.Holder<java.lang.Integer> totalAmount) {
        LOG.info("Executing operation totalAmount");
        System.out.println(totalAmount.value);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
